window.__ModuleLoader__.load({
  id: "dsh-web-mobile-fix",
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;

    var CSS = [
      "/* ── mobile UI fixes (≤700px) ── */",
      "@media (max-width: 700px) {",
      "  /* 1. Settings panel: stacked full-screen layout */",
      "  [role=\"dialog\"][aria-modal=\"true\"][aria-labelledby] {",
      "    flex-direction: column !important;",
      "    width: 100vw !important;",
      "    max-width: 100vw !important;",
      "    height: 100vh !important;",
      "    height: 100dvh !important;",
      "    max-height: 100vh !important;",
      "    max-height: 100dvh !important;",
      "    border-radius: 0 !important;",
      "  }",
      "  [role=\"dialog\"][aria-modal=\"true\"][aria-labelledby] > nav {",
      "    flex: none !important;",
      "    flex-direction: column !important;",
      "    width: 100% !important;",
      "    box-sizing: border-box !important;",
      "    padding: 12px 12px 6px !important;",
      "    gap: 8px !important;",
      "  }",
      "  [role=\"dialog\"][aria-modal=\"true\"][aria-labelledby] > nav > div:last-child {",
      "    flex-direction: row !important;",
      "    flex-wrap: nowrap !important;",
      "    gap: 6px !important;",
      "    overflow-x: auto !important;",
      "  }",
      "  [role=\"dialog\"][aria-modal=\"true\"][aria-labelledby] > nav button {",
      "    flex: 0 0 auto !important;",
      "    height: 36px !important;",
      "    padding: 6px 12px !important;",
      "    gap: 6px !important;",
      "    justify-content: center !important;",
      "  }",
      "  /* Keep every tab label visible: the stock label is flex:1 with",
      "        flex-basis 0, which collapses to zero width inside a content-sized",
      "        button; let the text drive the button width instead (0 1 auto). */",
      "  [role=\"dialog\"][aria-modal=\"true\"][aria-labelledby] > nav button > :last-child {",
      "    flex: 0 1 auto !important;",
      "    min-width: 0 !important;",
      "  }",
      "  [role=\"dialog\"][aria-modal=\"true\"][aria-labelledby] > nav button[aria-current=\"true\"] {",
      "    background: var(--dsw-specific-sidebar-nav-item-active, #e8ebf1) !important;",
      "  }",
      "  [role=\"dialog\"][aria-modal=\"true\"][aria-labelledby] > nav + div {",
      "    flex: 1 1 0 !important;",
      "    min-height: 0 !important;",
      "  }",
      "  [role=\"dialog\"][aria-modal=\"true\"][aria-labelledby] > nav + div > div:first-child {",
      "    padding: 12px 12px 6px !important;",
      "  }",
      "  [role=\"dialog\"][aria-modal=\"true\"][aria-labelledby] > nav + div > div:last-child {",
      "    padding: 0 16px 16px !important;",
      "  }",
      "  /* 2. Session log header button: compact icon-only circle */",
      "  [data-slot=\"conversation.session.header.utilities\"] button {",
      "    width: 32px !important;",
      "    min-width: 32px !important;",
      "    height: 32px !important;",
      "    padding: 0 !important;",
      "    border-radius: 50% !important;",
      "    justify-content: center !important;",
      "  }",
      "  [data-slot=\"conversation.session.header.utilities\"] button span {",
      "    position: absolute !important;",
      "    width: 1px !important;",
      "    height: 1px !important;",
      "    margin: -1px !important;",
      "    padding: 0 !important;",
      "    border: 0 !important;",
      "    overflow: hidden !important;",
      "    clip: rect(0 0 0 0) !important;",
      "    white-space: nowrap !important;",
      "  }",
      "  /* 3. Composer model select: hide the model name / effort text, keep the",
      "        chevron; the click still opens the model + effort picker */",
      "  [data-slot=\"conversation.input.model\"] > div > button {",
      "    padding: 0 6px !important;",
      "    gap: 0 !important;",
      "  }",
      "  [data-slot=\"conversation.input.model\"] > div > button > span {",
      "    display: none !important;",
      "  }",
      "  /* 5. Hide the session title breadcrumbs in the top bar */",
      "  [data-slot=\"conversation.session.header\"] nav {",
      "    display: none !important;",
      "  }",
      "  /* 6. Directory picker footer: pin Cancel/Open to one stable bottom row */",
      "  [role=\"dialog\"]:has(> div:last-child > button[aria-pressed]) > div:last-child {",
      "    display: grid !important;",
      "    grid-template-columns: minmax(0, 1fr) auto auto !important;",
      "    gap: 8px !important;",
      "    align-items: center !important;",
      "  }",
      "  [role=\"dialog\"]:has(> div:last-child > button[aria-pressed]) > div:last-child > :nth-child(1) {",
      "    grid-area: 1 / 1 !important;",
      "    justify-self: start !important;",
      "  }",
      "  [role=\"dialog\"]:has(> div:last-child > button[aria-pressed]) > div:last-child > :nth-child(2) {",
      "    grid-area: 1 / 2 !important;",
      "    justify-self: start !important;",
      "  }",
      "  [role=\"dialog\"]:has(> div:last-child > button[aria-pressed]) > div:last-child > :nth-child(3) {",
      "    grid-area: 2 / 1 !important;",
      "  }",
      "  [role=\"dialog\"]:has(> div:last-child > button[aria-pressed]) > div:last-child > :nth-child(4) {",
      "    grid-area: 2 / 2 !important;",
      "    justify-self: end !important;",
      "  }",
      "  [role=\"dialog\"]:has(> div:last-child > button[aria-pressed]) > div:last-child > :nth-child(5) {",
      "    grid-area: 2 / 3 !important;",
      "    justify-self: end !important;",
      "  }",
      "  /* 7. Left sidebar on narrow screens: keep the grid fixed at 56px rail in",
      "        BOTH states (center column never moves or squeezes) and let the",
      "        expanded sidebar OVERFLOW its 56px column to float over the center",
      "        (z-index 60 on the grid item) instead of positioning it absolutely.",
      "        No transform is applied: a transform on the sidebar column would",
      "        become the containing block for its position:fixed descendants —",
      "        the settings modal renders inside the sidebar DOM and would be",
      "        trapped/positioned relative to the drawer instead of the viewport.",
      "        The product's own wide-sidebar interactions (rail buttons, search",
      "        focus, settings dialog) keep working natively, and the stock",
      "        wide-content fade-in remains the only animation. */",
      "  [data-details-collapsed] {",
      "    grid-template-columns: 56px minmax(0, 1fr) 0 !important;",
      "  }",
      "  [data-details-collapsed]:not([data-sidebar-collapsed]) > div:first-child {",
      "    overflow: visible !important;",
      "    z-index: 60 !important;",
      "  }",
      "}",
    ].join("\n");

    function apply(ctx) {
      var tag = document.createElement("style");
      tag.dataset.plugin = "dsh-web-mobile-fix";
      tag.textContent = CSS;
      document.head.append(tag);
      ctx.effect(function () {
        return function () { tag.remove() };
      });
    }

    exports.apply = apply;
    return module.exports;
  }
});
